import './globals.css';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Poppins } from 'next/font/google';
import { auth } from '@/auth';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';

// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ["latin"] });

const fontSans = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(fontSans.className)} suppressHydrationWarning>
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
